cesa:
  target: databricks_cluster
  outputs:
    databricks_cluster:
      type: databricks
      catalog: workspace
      schema: cesadev
      host: dbc-d41ae76e-e3c3.cloud.databricks.com
      http_path: /sql/1.0/warehouses/7ebe4244813e7d05
      token: "{{ env_var('dbt-token') }}"
      threads: 8
